# Generated by Django 6.0.1 on 2026-02-19 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('business_address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='suppliers/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
