# Generated by Django 6.0.3 on 2026-03-06 05:43

import django.contrib.sessions.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='session',
            managers=[
                ('objects', django.contrib.sessions.models.SessionManager()),
            ],
        ),
    ]
