# Generated by Django 6.0.2 on 2026-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_is_paid_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='CARD', max_length=20),
        ),
    ]
