# Generated by Django 6.0.1 on 2026-02-24 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0005_product_cost_price_product_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gold_weight', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('purity', models.CharField(choices=[('18K', '18 Karat'), ('22K', '22 Karat'), ('24K', '24 Karat')], default='22K', max_length=10)),
                ('diamond_clarity', models.CharField(blank=True, choices=[('IF', 'Internally Flawless'), ('VVS1', 'Very Very Slightly Included 1'), ('VVS2', 'Very Very Slightly Included 2'), ('VS1', 'Very Slightly Included 1'), ('VS2', 'Very Slightly Included 2'), ('SI1', 'Slightly Included 1'), ('SI2', 'Slightly Included 2'), ('I1', 'Included 1')], max_length=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='categories.category')),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_store_product', to='products.supplierproduct'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='supplier_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.supplierproduct'),
        ),
    ]
