# Generated by Django 6.0.1 on 2026-02-24 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_product_supplierproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available_for_sale',
            field=models.BooleanField(default=False, help_text='Strict: True only if stock is received by Admin'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot of the price admin pays to supplier', max_digits=12),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('PURCHASE', 'Inventory Purchase'), ('SALE', 'Retail Sale'), ('ADJUSTMENT', 'Stock Adjustment'), ('RETURN', 'Customer Return'), ('CANCEL', 'Order Cancellation')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('reference_id', models.CharField(help_text='PO ID, Order ID, or Adjustment Reason', max_length=100)),
                ('previous_stock', models.IntegerField()),
                ('current_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
